Repository lucky-treee/diamond, pull requests merged in 2023-03, with the labels that each got.

#25 feature/#21 [카카오 API 주소 수정]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/KakaoUserInfoFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
Labels: 🎨 Style, 🛠️ Refactor

#26 feature/#21 카카오 로그인 테스트
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoTokenResponse.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
Labels: 🎨 Style, 🐞 Fix

#27 feature/#21 [카카오 응답객체 필드명 수정]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoTokenResponse.java
Labels: 🐞 Fix

#28 feature/#21 [카카오 응답객체 필드 수정]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoAccount.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoUserInfo.java
Labels: 🐞 Fix

#29 feature/#21 [카카오 유저 리소스 응답 필드값 추가]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoAccount.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoUserInfo.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
Labels: 🐞 Fix, 💻 Chore

#21 feature/#55 [Controller, Port, Adapter, Service, UseCase 통합]
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/persistence/ShopAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
Labels: 🎨 Style

#30 feature/#53 Swagger 업그레이드
  shop_service/src/main/java/com/luckytree/shop_service/common/config/SwaggerConfig.java
  shop_service/src/main/java/com/luckytree/shop_service/common/dto/ResultResponse.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopRequest.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/RemoveRequestForm.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/domain/ShopDetail.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/domain/ShopSummary.java
Labels: 📃 Docs

#39 feature/#33 샵 리뷰 수정
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/UpdateReviewDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
Labels: ➕ Feature

#41 feature/#34 샵 리뷰 조회
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
Labels: ➕ Feature

#42 feature/#35 샵 리뷰 삭제
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
Labels: ➕ Feature

#36 feature/#1 샵 즐겨찾기 해제
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
Labels: ➕ Feature

#37 feature/#13 샵 즐겨찾기 목록 조회
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/ShopDetailDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
Labels: ➕ Feature

#43 feature/#24 [로그인 응답객체의 쿠키에 토큰 셋팅]
  member_service/src/main/java/com/luckytree/member_service/common/advice/NotFoundException.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/AuthenticationAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/token/TokenAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
Labels: 🎨 Style, ➕ Feature

#44 feature/#9 [내 프로필 조회 기능 리팩토링]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/MemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Member.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/MemberProfile.java
Labels: 🛠️ Refactor

#22 feature/#6 회원 탈퇴 기능 구현
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/MemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Status.java
Labels: ➕ Feature

#46 feature/#6 [회원 탈퇴 API 구현]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/MemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Status.java
Labels: ➕ Feature

#48 feature/#13 [즐겨찾기 조회 API 구현]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/BookmarkDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/Category.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/MyBookmarksDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/ShopDetailDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/ShopFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/ShopFeignClientAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/BookmarkEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/BookmarkIdInterface.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/BookmarkRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/BookmarkController.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/AuthenticationUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/AuthenticationPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/MemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/ShopFeignClientPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/TokenPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Hashtag.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/BookmarkDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/MyBookmarksDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopDetailDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/persistence/ShopAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/persistence/ShopEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/persistence/ShopRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/internal/InternalBookmarkController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
Labels: 🐞 Fix, ➕ Feature

#51 feature/#30 [@ApiResponse를 Swaggerconfig를 통해서 globalResponseMessage로 수정] (Member)
  member_service/src/main/java/com/luckytree/member_service/common/config/SwaggerConfig.java
Labels: ➕ Feature

#53 feature/#52 [카카오 로그인의 파라미터로 Redirect Uri 를 받는다]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoLoginDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/AuthenticationAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/AuthenticationUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/AuthenticationPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
Labels: ➕ Feature

#57 feature/#54 [샵 서비스 리팩토링 1차]
  shop_service/src/main/java/com/luckytree/shop_service/common/advice/ControllerAdvice.java
  shop_service/src/main/java/com/luckytree/shop_service/common/exceptions/BadRequestException.java
  shop_service/src/main/java/com/luckytree/shop_service/common/exceptions/InternalServerErrorException.java
  shop_service/src/main/java/com/luckytree/shop_service/common/exceptions/NotFoundException.java
  shop_service/src/main/java/com/luckytree/shop_service/common/exceptions/UnAuthorizedException.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/persistence/CreateShopPersistenceAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/persistence/GetShopListPersistenceAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/persistence/RemoveShopPersistenceAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/CreateShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/GetShopListController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/RemoveShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/CreateShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/GetShopListUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/RemoveShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/CreateShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/GetShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/RemoveShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/CreateShopService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/GetShopListService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/RemoveShopService.java
Labels: 🛠️ Refactor

#58 feature/#54 [샵 서비스 리팩토링 2차]
  shop_service/src/main/java/com/luckytree/shop_service/common/config/SwaggerConfig.java
  shop_service/src/main/java/com/luckytree/shop_service/common/dto/ResultResponse.java
  shop_service/src/main/java/com/luckytree/shop_service/common/enums/Category.java
  shop_service/src/main/java/com/luckytree/shop_service/common/enums/Hashtag.java
  shop_service/src/main/java/com/luckytree/shop_service/common/enums/ShopStatus.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/ShopAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/BookmarkDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopDetail.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopDetailDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopRequest.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopSummary.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/feign/MemberFeignClient.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/feign/MemberFeignClientPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/BaseTimeEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ShopEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ShopRemoveEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ShopRemoveRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ShopRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/internal/InternalBookmarkController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/domain/Shop.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/domain/ShopStatus.java
Labels: 🛠️ Refactor

#59 feature/#54 [샵 서비스 리팩토링 3차]
  member_service/build.gradle.kts
  shop_service/build.gradle.kts
  shop_service/src/main/java/com/luckytree/shop_service/common/annotation/AuthorizationArgumentResolver.java
  shop_service/src/main/java/com/luckytree/shop_service/common/annotation/LoginMemberId.java
  shop_service/src/main/java/com/luckytree/shop_service/common/jwt/TokenProvider.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/ShopAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/CreateReviewDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/CreateShopDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopDeleteDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopDetail.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopDetailDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopSearchDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopSummaryDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ShopEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/domain/Review.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/domain/Shop.java
Labels: 🛠️ Refactor

#60 hotfix/1.0.1
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/ShopFeignRequestDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/ShopFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/ShopFeignClientAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ShopFeignResponseDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/internal/InternalBookmarkController.java
Labels: ⚠️ Hotfix

#66 feature/#63 [사진 자료형 변경 + 로그인 헤더 오류 수정]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/SignupDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/UpdateMemberDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Member.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/MemberProfile.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Photo.java
Labels: 🐞 Fix

#65 feature/#2 [즐겨찾기 등록 api 구현]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/MemberFeignRequestDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/MemberFeignResponseDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/BookmarkEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/internal/internalBookmarkController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/MemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Bookmark.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/ShopAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/MemberFeignRequestDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/feign/MemberFeignClient.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/feign/MemberFeignClientAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ShopRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/BookmarkController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/MemberFeignClientPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
Labels: ➕ Feature

#67 change gradle
  member_service/build.gradle.kts
  shop_service/build.gradle.kts
Labels: ⚙ Bulid

#68 빌드 그래들 변경 2트..
  member_service/build.gradle.kts
  shop_service/build.gradle.kts
Labels: ⚙ Bulid

#64 feature/#1 [마이페이지에서 내 북마크 해제 기능 api 구현]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/BookmarkAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/BookmarkRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/BookmarkController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/BookmarkPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/feign/MemberFeignClient.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/feign/MemberFeignClientAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/feign/MemberFeignClientPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/BookmarkController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/MemberFeignClientPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
Labels: ➕ Feature

#73 feature/#55 [멤버 서비스 리팩토링 2차]
  member_service/src/main/java/com/luckytree/member_service/common/config/KakaoFeignConfiguration.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/MemberResponse.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/AuthenticationAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/KakaoTokenFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/jpa/BookmarkAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/jpa/BookmarkEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/jpa/BookmarkRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/jpa/MemberAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/jpa/MemberEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/jpa/MemberRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/BookmarkIdInterface.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/BookmarkPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/MemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/BookmarkService.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Member.java
Labels: 🎨 Style, 🛠️ Refactor, 💻 Chore

#75 feature/#56 [레디스 적용 리프레시토큰 저장 기능 구현]
  member_service/build.gradle.kts
  member_service/src/main/java/com/luckytree/member_service/common/config/RedisConfiguration.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/redis/RedisAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/RedisPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
Labels: ➕ Feature

#81 feature/#21 [토큰 재발급 구현]
  member_service/src/main/java/com/luckytree/member_service/common/jwt/TokenProvider.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/redis/RedisAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/token/TokenAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/AuthenticationUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/RedisPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/TokenPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
Labels: ➕ Feature

#82 feature/#21 [레디스 config repo 추가]
  member_service/src/main/resources/application.yml
Labels: ⚙ Bulid
