Repository lucky-treee/diamond, pull requests merged in 2023-05, with the labels that each got.

#104 chore: remove Auth feature in Member service
  member_service/build.gradle.kts
  member_service/src/main/java/com/luckytree/member_service/common/config/KakaoFeignConfiguration.java
  member_service/src/main/java/com/luckytree/member_service/common/config/RedisConfiguration.java
  member_service/src/main/java/com/luckytree/member_service/common/jwt/TokenProvider.java
  member_service/src/main/java/com/luckytree/member_service/common/utils/TokenUtil.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoAccount.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoTokenRequest.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoTokenResponse.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoUserInfo.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/LoginRequest.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/SignupRequest.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/Tokens.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/AuthenticationAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/KakaoTokenFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/KakaoUserInfoFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/redis/RedisAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/token/TokenAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/BookmarkController.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/AuthenticationUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/BookmarkUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/AuthenticationPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/RedisPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/TokenPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/BookmarkService.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
Labels: 💻 Chore

#103 [feature] #33 리뷰 수정 api 구현
  shop_service/build.gradle.kts
  shop_service/src/main/java/com/luckytree/shop_service/common/config/AwsConfig.java
  shop_service/src/main/java/com/luckytree/shop_service/common/utils/S3Util.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/ReviewAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/CreateReviewDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/CreateReviewPhotoDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/UpdateReviewDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/UpdateReviewPhotoDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewPhotoEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewPhotoRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ReviewController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ReviewUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ReviewPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ReviewService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/domain/Review.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/domain/ReviewPhoto.java
Labels: ➕ Feature

#105 [feature ]#35 리뷰 삭제 api 구현
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/ShopFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/ShopFeignClientAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/ReviewController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/ReviewUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/ShopFeignClientPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/ReviewService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/ReviewAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewPhotoEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewPhotoRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/internal/internalReviewController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ReviewUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ReviewPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ReviewService.java
Labels: ➕ Feature

#106 [feature]#34 내 리뷰 조회 api 구현
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/ReviewResponse.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/ReviewsResponse.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/ShopFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/ShopFeignClientAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/jpa/MemberAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/ReviewController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/ReviewUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/MemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/ShopFeignClientPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/ReviewService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/ReviewAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/MyReviewsDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/ReviewDto.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewPhotoEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ReviewRepository.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/jpa/ShopEntity.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/internal/internalReviewController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ReviewUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ReviewPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ReviewService.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
Labels: ➕ Feature, 💻 Chore

#107 feat: auth & core
  .gradle/file-system.probe
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/KakaoFeignRepository.kt
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/KakaoTokenFeignClient.kt
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/KakaoUserFeignClient.kt
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/data/GetKakaoTokenRequest.kt
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/data/GetKakaoTokenResponse.kt
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/data/GetKakaoUserEmailRequest.kt
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/data/GetKakaoUserEmailResponse.kt
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/data/GetKakaoUserResponse.kt
  auth/src/main/kotlin/com/example/auth/client/feign/kakao/data/KakaoAccount.kt
  auth/src/main/kotlin/com/example/auth/client/feign/member/MemberFeignClient.kt
  auth/src/main/kotlin/com/example/auth/client/feign/member/MemberFeignRepository.kt
  auth/src/main/kotlin/com/example/auth/client/feign/member/data/MemberFeignRequest.kt
  auth/src/main/kotlin/com/example/auth/client/feign/member/data/MemberFeignResponse.kt
  auth/src/main/kotlin/com/example/auth/config/InternalFeignConfig.kt
  auth/src/main/kotlin/com/example/auth/controller/AuthController.kt
  auth/src/main/kotlin/com/example/auth/domain/member/AccessTokenResponse.kt
  auth/src/main/kotlin/com/example/auth/domain/member/GenerateTokenRequest.kt
  auth/src/main/kotlin/com/example/auth/domain/member/Member.kt
  auth/src/main/kotlin/com/example/auth/model/entity/Authority.kt
  auth/src/main/kotlin/com/example/auth/model/entity/Member.kt
  auth/src/main/kotlin/com/example/auth/persistence/AuthorityRepository.kt
  auth/src/main/kotlin/com/example/auth/persistence/MemberRepository.kt
  auth/src/main/kotlin/com/example/auth/service/AuthService.kt
  auth/src/main/kotlin/com/example/auth/service/Jwt.kt
  auth/src/main/kotlin/com/example/auth/util/SecurityUtil.kt
  auth/src/main/kotlin/com/example/auth/util/TokenProvider.kt
  core/src/main/kotlin/luckytree/poom/core/config/CorsConfig.kt
  core/src/main/kotlin/luckytree/poom/core/config/ExternalFeignConfig.kt
  core/src/main/kotlin/luckytree/poom/core/config/JwtConfiguration.kt
  core/src/main/kotlin/luckytree/poom/core/config/JwtSecurityConfig.kt
  core/src/main/kotlin/luckytree/poom/core/config/SecurityConfig.kt
  core/src/main/kotlin/luckytree/poom/core/exceptions/NotFoundException.kt
  core/src/main/kotlin/luckytree/poom/core/filter/JwtFilter.kt
  core/src/main/kotlin/luckytree/poom/core/handler/JwtAccessDeniedHandler.kt
  core/src/main/kotlin/luckytree/poom/core/handler/JwtAuthenticationEntryPoint.kt
  core/src/main/kotlin/luckytree/poom/core/jwt/AuthenticationToken.kt
  core/src/main/kotlin/luckytree/poom/core/jwt/Claims.kt
  core/src/main/kotlin/luckytree/poom/core/jwt/JwtAuthentication.kt
  core/src/main/kotlin/luckytree/poom/core/jwt/Role.kt
  core/src/main/kotlin/luckytree/poom/core/jwt/Token.kt
  core/src/main/kotlin/luckytree/poom/core/service/TokenProvider.kt
  core/src/main/kotlin/luckytree/poom/core/util/SecurityUtil.kt
  member_service/src/main/resources/application-local.yml
Labels: ➕ Feature

#109 style: 코틀린 코드 스타일 적용
  auth/src/main/kotlin/com/example/auth/client/feign/member/MemberFeignClient.kt
  auth/src/main/kotlin/com/example/auth/config/InternalFeignConfig.kt
  auth/src/main/kotlin/com/example/auth/domain/member/GenerateTokenRequest.kt
Labels: 🎨 Style

#110 feature/#100-POOM-SECURITY
  build.gradle.kts
  core/build.gradle.kts
  core/src/main/kotlin/luckytree/poom/core/config/SecurityConfig.kt
  core/src/main/kotlin/luckytree/poom/core/filter/InternalKeyFilter.kt
  core/src/main/kotlin/luckytree/poom/core/filter/InternalKeyManager.kt
  member_service/build.gradle.kts
  shop_service/build.gradle.kts
Labels: ⚙ Bulid, ➕ Feature

#111 build: core setting
  auth/src/main/resources/application.yml
  core/src/main/resources/application-core.yml
  core/src/main/resources/application.yml
Labels: ⚙ Bulid

#113 [refactor]#34 내 리뷰 찾기 api 파라미터 수정
  shop/src/main/java/com/luckytree/shop/common/utils/S3Util.java
  shop/src/main/java/com/luckytree/shop/shop/adapter/data/review/ReviewResponse.java
  shop/src/main/java/com/luckytree/shop/shop/adapter/jpa/review/ReviewEntity.java
  shop/src/main/java/com/luckytree/shop/shop/adapter/jpa/review/ReviewPhotoEntity.java
  shop/src/main/java/com/luckytree/shop/shop/adapter/web/ReviewController.java
  shop/src/main/java/com/luckytree/shop/shop/application/port/incoming/ReviewUseCase.java
  shop/src/main/java/com/luckytree/shop/shop/application/service/ReviewService.java
Labels: 🛠️ Refactor

#114 [feature]#33 Swagger
  member/src/main/java/com/luckytree/member/config/SwaggerConfig.java
  shop/src/main/java/com/luckytree/shop/common/config/SwaggerConfig.java
Labels: ➕ Feature
