Repository lucky-treee/diamond, pull requests merged in 2023-04, with the labels that each got.

#83 feature/#79 [샵 등록 성공케이스 테스트 코드 구현]
  shop_service/src/main/java/com/luckytree/shop_service/common/jwt/TokenProvider.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/test/java/com/luckytree/shop_service/shop/adapter/web/ShopControllerTest.java
Labels: ✅ Test

#87 feature/#00 [CORS 설정 변경]
  shop_service/src/main/java/com/luckytree/shop_service/common/config/CorsConfig.java
Labels: 🐞 Fix

#90 feature/#00 [로그인 500 에러 해결]
  member_service/src/main/java/com/luckytree/member_service/common/config/RedisConfiguration.java
Labels: 🐞 Fix

#84 feature/#79 [샵 서비스 가게 등록 로직 테스트 코드 구현]
  shop_service/src/test/java/com/luckytree/shop_service/shop/application/service/ShopServiceTest.java
Labels: ✅ Test

#89 feature/#88 [shop_service swagger LocalDateTime을 Time 형식으로 변환.]
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/data/CreateShopDto.java
Labels: 💻 Chore

#91 feature#00 [레디스 설정에 패스워드 추가]
  member_service/src/main/java/com/luckytree/member_service/common/config/RedisConfiguration.java
  member_service/src/main/resources/application.yml
Labels: 🐞 Fix

#92 feature/#00 [레디스 프로파일 수정]
  member_service/src/main/resources/application.yml
Labels: 🐞 Fix

#94 feature/#93 [can't parse json 이슈 해결]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/Tokens.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
Labels: 🐞 Fix

#86 feature/#76 [샵 이름과 주소로 상세조회를 샵 아이디로 상세조회로 대체]
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/ShopAdapter.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/BookmarkController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/outgoing/ShopPort.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
Labels: ➕ Feature

#74 feature/#61 [swagger summary에 (로그인) 추가]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/BookmarkController.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/BookmarkController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
Labels: 🎨 Style

#85 feature/#78 [내부 api 엔드 포인트 internal keyword 제거]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/internal/internalBookmarkController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/feign/MemberFeignClient.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/BookmarkController.java
Labels: 💻 Chore

#96 feature/#95 [리프레시 토큰 쿠키 설정 해결]
  member_service/src/main/java/com/luckytree/member_service/common/jwt/TokenProvider.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
Labels: 🐞 Fix

#98 feature#97 [API 요청시 토큰 인증 방식 변경]
  member_service/src/main/java/com/luckytree/member_service/common/annotation/AuthorizationArgumentResolver.java
  member_service/src/main/java/com/luckytree/member_service/common/annotation/LoginMemberId.java
  member_service/src/main/java/com/luckytree/member_service/common/utils/TokenUtil.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/BookmarkController.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/BookmarkUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/MemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/BookmarkService.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/MemberService.java
  shop_service/src/main/java/com/luckytree/shop_service/common/annotation/AuthorizationArgumentResolver.java
  shop_service/src/main/java/com/luckytree/shop_service/common/annotation/LoginMemberId.java
  shop_service/src/main/java/com/luckytree/shop_service/common/utils/TokenUtil.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/BookmarkController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/web/ShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/port/incoming/ShopUseCase.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/application/service/ShopService.java
Labels: 🐞 Fix, ➕ Feature, 🛠️ Refactor

#99 feature#97 [토큰 인터페이스 수정]
  member_service/src/main/java/com/luckytree/member_service/common/config/WebConfig.java
Labels: 🐞 Fix
