Repository lucky-treee/diamond, pull requests merged in 2023-02, with the labels that each got.

#3 feature/#9 [Entity 및 DTO 생성]
  member_service/src/main/java/com/luckytree/member_service/common/dto/ResultResponse.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/out/persistence/MemberEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/out/persistence/MemberRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Status.java
Labels: ➕ Feature

#5 feature/#3 [Photo 필드 및 entity 필드 수정]
  member_service/build.gradle.kts
  member_service/src/main/java/com/luckytree/member_service/member/domain/Photo.java
Labels: ➕ Feature

#8 feature/#18 Entity에 createAt, updateAt 추가 구현
  member_service/src/main/java/com/luckytree/member_service/member/adapter/out/ControllerAdvice.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/out/persistence/MemberEntity.java
Labels: ➕ Feature

#9 feature/#9 [회원 상세정보 조회 api 구현]
  member_service/src/main/java/com/luckytree/member_service/common/ControllerAdvice.java
  member_service/src/main/java/com/luckytree/member_service/common/config/FeignClientConfig.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/FeignClients.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/out/persistence/MemberRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/GetMemberPersistenceAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/GetMemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/GetMemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/GetMemberService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/MemberProfile.java
  member_service/src/main/resources/application.yml
Labels: ⚙ Bulid, ➕ Feature, 💻 Chore

#11 feature/#3 jwt 활용 회원가입 기능 구현
  member_service/build.gradle.kts
  member_service/src/main/java/com/luckytree/member_service/common/ControllerAdvice.java
  member_service/src/main/java/com/luckytree/member_service/common/advice/ControllerAdvice.java
  member_service/src/main/java/com/luckytree/member_service/common/dto/ResultResponse.java
  member_service/src/main/java/com/luckytree/member_service/common/jwt/TokenProvider.java
  member_service/src/main/java/com/luckytree/member_service/email/adapter/in/MailSendController.java
  member_service/src/main/java/com/luckytree/member_service/email/application/service/MailService.java
  member_service/src/main/java/com/luckytree/member_service/email/domain/Mail.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/AuthenticateResult.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/SignupDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/TokenDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/AuthenticationAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/GetMemberPersistenceAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberEntity.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/AuthenticationUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/AuthenticationPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Authentication.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Member.java
  member_service/src/main/resources/application.yml
Labels: ➕ Feature

#13 feature/#19 swagger 의존성 주입
  member_service/build.gradle.kts
Labels: ⚙ Bulid

#14 feature/#53 API versioning 진행.
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/in/web/CreateShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/in/web/GetShopListController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/in/web/RemoveShopController.java
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/in/web/ShopController.java
Labels: 💻 Chore

#15 jwt 설정 긴급 배포
  member_service/src/main/java/com/luckytree/member_service/common/advice/ControllerAdvice.java
  member_service/src/main/java/com/luckytree/member_service/common/jwt/TokenProvider.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/AuthenticateResult.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/LoginDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/AuthenticationUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
  member_service/src/main/java/com/luckytree/member_service/member/domain/Authentication.java
  member_service/src/main/resources/application.yml
Labels: ⚠️ Hotfix

#16 hotfix/0.0.1
  member_service/src/main/java/com/luckytree/member_service/common/jwt/TokenProvider.java
  member_service/src/main/resources/application.yml
Labels: ⚠️ Hotfix

#18 feature/#53 API Versioning 추가
  shop_service/src/main/java/com/luckytree/shop_service/shop/adapter/in/web/ShopController.java
Labels: 💻 Chore

#19 feature/#19 member_service api 진행
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/GetMemberPersistenceAdapter.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/persistence/MemberRepository.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/MemberProfileController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/GetMemberUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/outgoing/GetMemberPort.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/GetMemberService.java
Labels: 💻 Chore

#20 feature/#15 [카카오 로그인 기능 구현 및 기존 회원가입 로그인 리팩토링]
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoAccount.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoTokenRequest.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoTokenResponse.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/KakaoUserInfo.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/data/LoginDto.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/KakaoFeignConfiguration.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/KakaoTokenFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/feign/KakaoUserInfoFeignClient.java
  member_service/src/main/java/com/luckytree/member_service/member/adapter/web/AuthController.java
  member_service/src/main/java/com/luckytree/member_service/member/application/port/incoming/AuthenticationUseCase.java
  member_service/src/main/java/com/luckytree/member_service/member/application/service/AuthenticationService.java
Labels: 🎨 Style, ➕ Feature, 🛠️ Refactor
